version: '3'
services:
  db:
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: story_production
    volumes:
      - ./config/mysql.cnf:/etc/mysql/conf.d/custom.cnf
      - ./db/vol:/var/lib/mysql
  web:
    build: .
    entrypoint:
      - ./bin/entry_point.sh
    command: ["rails","server","-b","0.0.0.0","-p","3000"]
    env_file:
      - '.env.web'
    volumes:
      - .:/storyapp
    ports:
      - "3000:3000"
    links:
      - db